### ISSUE TITLE
JSException: ReferenceError: Can't find variable: dahuapp

### ISSUE THREAD

**Issue by moy** [dahuapp/dahu#108]
With the tip of branch next, I'm getting the following error when the editor starts:

```
Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: ReferenceError: Can't find variable: dahuapp
        at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128)
        at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
        at com.sun.webkit.WebPage.executeScript(WebPage.java:1410)
        at javafx.scene.web.WebEngine.executeScript(WebEngine.java:934)
        at io.dahuapp.common.javascript.WebEngineRuntime.executeScriptCommand(WebEngineRuntime.java:38)
        at io.dahuapp.editor.DahuApp$1.changed(DahuApp.java:142)
        at io.dahuapp.editor.DahuApp$1.changed(DahuApp.java:123)
```

The offending line is:

```
                    // start application
                    webEngineRuntime.executeScriptCommand("dahuapp.start();");
```

It bisects to 0a9a8ee, in particular this hunk:

``` diff
diff --git a/dahu/core/app/scripts/views/workspace/screen.js b/dahu/core/app/scripts/views/workspace/screen.js
index 53efa23..2df9b3e 100644
--- a/dahu/core/app/scripts/views/workspace/screen.js
+++ b/dahu/core/app/scripts/views/workspace/screen.js
@@ -5,6 +5,7 @@
 define([
     'handlebars',
     'backbone.marionette',
+    'fit',
     // modules
     'modules/events',
     'modules/requestResponse',
@@ -21,6 +22,7 @@ define([
 ], function(
     Handlebars,
     Marionette,
+    fit,
     // modules
     events,
     reqres,
```

Surprisingly, if I apply this patch, the bug also disappears (but if I name the require.js module explicitly with the right name 'views/workspace/screen' instead of just 'screen', the bug comes back):

``` diff
--- a/dahu/core/app/scripts/views/workspace/screen.js
+++ b/dahu/core/app/scripts/views/workspace/screen.js
@@ -2,7 +2,7 @@
  * Created by barraq on 26/05/14.
  */

-define([
+define('screen', [
     'handlebars',
     'backbone.marionette',
     'fit',
```

All this on Linux Debian, java version "1.8.0_11"
Any idea?

**Comment by barraq** [comment]
Hi @moy, the `ReferenceError: Can't find variable: dahuapp` appears whenever RequireJS is missing some modules or that something went wrong with some module initialization. As a consequence the main dahuapp module is not initialized correctly which then justify why the following fails `webEngineRuntime.executeScriptCommand("dahuapp.start();");`.

I tracked the bug down and it is due to this missing Fit.js ! (or also due to loading the wrong fit as in #107). This is bug is closed with 143125c. Sorry for that.
