### ISSUE TITLE
Dahu does not exit on close

### ISSUE THREAD

**Issue by twitwi** [dahuapp/dahu#113]
After I stop Dahu (0.3 Linux 64, jdk8_20), the java command does not exit.

Using the jvisualvm, the only thread that is not a daemon is the following

```
"pool-3-thread-1" #100 prio=5 os_prio=0 tid=0x00007f4b9c1b2800 nid=0x42d3 waiting on condition [0x00007f4bab747000]
   java.lang.Thread.State: WAITING (parking)
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x00000000dc7992e8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
    at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
    at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by twitwi** [comment]
This problem occurs only if I started a "Preview" at some point. This is most probably a problem with the code that starts the browser.

**Comment by barraq** [comment]
Thanks @twitwi for reporting this issue ;) Regarding Dahu-Next I am actually re-writing lot of things that were badly designed (this is a student project), it'is a big "sac de noeuds" that I didn't yet finished to unwrap! I hope to push the first commits next week :) I'll include this issue in the things to patch. If you wish to contribute at some point let me know so that we can better coordinate.

**Comment by beckerdenis** [comment]
I'm fixing it, as @twitwi said it's a bug about a bad management of the browser launching.
